name: pymeasure
channels:
  - conda-forge
dependencies:
  - cloudpickle=1.6.0
  - numpy=1.26.4
  - pandas=2.2.2
  - pint=0.24
  - pyqt=5.15.7
  - pyqtgraph=0.13.7
  - pyserial=3.5
  - pyvisa=1.14.1
  - pyzmq=26.0.3
  - qt=5.15.6
# Development dependencies below
  - pytest-qt=4.4.0
  - pytest-runner=6.0.0
  - pytest=8.2.2
  - pytest-cov=5.0.0
  - pyvisa-sim==0.6.0
  - flake8=7.0.0
  - setuptools_scm==8.1.0 # don't pin, to get newest features
  - sphinx=5.3.0
  - sphinx_rtd_theme=1.2.2
#  pip is currently not needed, but the recommended tool when packages that are unavailable on conda are required
#  - pip  # don't pin, to gain newest conda compatibility fixes
