repos:
- repo: https://github.com/akaihola/darker
  rev: v2.1.1
  hooks:
    - id: darker
      args:
        - --color
        - --quiet
        - --isort
        - --lint
        - flake8
        # - --lint
        # - pylint
      additional_dependencies:
        - black
        - isort
        - flake8==6.0.0
        - pylint
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
    - id: flake8